### ISSUE TITLE
Can the descriptor head be used alone?

### ISSUE THREAD

**Issue by bfialkoff** [ruc-aimc-lab/SuperRetina#2]
Is there a simple way to use only the descriptor head so this can be used as a dense feature extractor?
Can I specify the keypoint and have the network give me its descriptor?

**Comment by jiazhen-code** [comment]
The output of the descriptor is dense. To meet your requirement (i.e., specificy keypoints and let the network give their descriptors), you may run SuperRetina and simply ignore the output of the detector head. That shall do the job. 
The pseudocode is like this:

```

keypoints = your_keypoint_detection(input_image) 

with torch.no_grad():
    detector_pred, descriptor_pred = model(input_image)

full_desc_map = nn.Upsample(scale_factor=8, mode='bilinear', align_corners=True)(descriptor_pred)

desc_list = full_desc_map[keypoints]

```
