### ISSUE TITLE
Paper mAUC vs Code mAUC

### ISSUE THREAD

**Issue by NiharGupte** [ruc-aimc-lab/SuperRetina#3]
Paper states that the mAUC of SuperRetina is 0.755, whereas the code returns 0.762, why is there such a difference?

**Comment by jiazhen-code** [comment]
Hello, the difference in mRUC lies in the utilization of certain techniques (secondary matching) in the project to showcase strategies that can further enhance performance. You can disable these strategies by setting "use_matching_trick" to false in the YAML configuration file.
