### ISSUE TITLE
About training dataset "Lab" 

### ISSUE THREAD

**Issue by JachyLikeCoding** [ruc-aimc-lab/SuperRetina#4]
Hi, Jiazhen. I came across this SuperRetina project and paper, and I am particularly interested in your training dataset "Lab". I am currently conducting research in a related field. I would like to inquire if it is possible to obtain access to your training dataset. I assure you that I will strictly adhere to any applicable data usage guidelines and will only use the data for academic research purposes.
Looking forward to your response.
My Email: 1098587201@qq.com

**Comment by jiazhen-code** [comment]
Hello, the Lab dataset was collected from private users, and we do not plan to make it publicly available. Instead, I suggest you use the intersection detection tool to create similar Lab data (even SIFT keypoints should work well).
